networks:
  default:
    name: '${DOCKER_NAME}-network'
    driver: bridge

services:
  app:
    container_name: '${DOCKER_NAME}-app'
    build:
      context: ./
      dockerfile: dockerfile
      args:
        NODEVERSION: '${DOCKER_NODE_VERSION}'
        WWWGROUP: '${DOCKER_GID}'
        TIMEZONE: '${DOCKER_TIMEZONE}'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${DOCKER_UID}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      APP_HOST_INTERNAL_PORT: '${DOCKER_APP_HOST_INTERNAL_PORT}'
    ports:
      - '${DOCKER_APP_HOST_EXTERNAL_PORT}:80'
    volumes:
      - ../:/app/
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf
      - ./nginx/html:/etc/nginx/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - default
